remote_theme: pages-themes/time-machine@v0.2.0
title: Passion Project
description: This is where I share all the fun and interesting things about my life and things I am most passionate about!
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onetitle: Razi Messinger Blog and Passions!
